apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-apps
  template:
    metadata:
      labels:
        app: todo-apps
    spec:
      containers:
        - name: todo-apps
          image: PROJECT/IMAGE #docker image for todo-apps get from docker hub
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          env:
            - name: NATS_URL
              value: nats://my-nats.default.svc.cluster.local:4222
          # resources:
          #   requests:
          #     cpu: "10m"
          #     memory: "16Mi"
          #   limits:
          #     cpu: "100m"
          #     memory: "64Mi"
          # readinessProbe:
          #   initialDelaySeconds: 10 # Initial delay until the readiness is tested
          #   periodSeconds: 5 # How often to test
          #   httpGet:
          #     path: /todos
          #     port: 3001
