apiVersion: apps/v1
kind: Deployment
metadata:
  name: hourly-image
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hourly-image
  template:
    metadata:
      labels:
        app: hourly-image
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: hourly-image-pvc
      containers:
        - name: hourly-image
          image: PROJECT/IMAGE
          env: # Set environment variable from ConfigMap
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: hourly-image-config
                  key: PORT
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: hourly-image-config
                  key: IMAGE_URL
            - name: TODO_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: hourly-image-config
                  key: TODO_SERVICE_URL

          volumeMounts: # Mount volume
            - name: shared-storage
              mountPath: /src/app/files
          # readinessProbe:
          #   initialDelaySeconds: 10 # Initial delay until the readiness is tested
          #   periodSeconds: 5 # How often to test
          #   httpGet:
          #     path: /
          #     port: 3000
