apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: STAGING_MODE
        value: "false"
  target:
    kind: Deployment
    name: broadcaster
sortOptions:
  order: fifo
images:
- name: PROJECT/IMAGE
  newName: cupaxxhd/broadcaster
- name: cupaxxhd/broadcaster
  newName: cupaxxhd/broadcaster
  newTag: "4.9"
