apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
sortOptions:
  order: fifo
images:
- name: PROJECT/IMAGE
  newName: cupaxxhd/hourly-image
- name: cupaxxhd/hourly-image
  newName: cupaxxhd/hourly-image
  newTag: e79af4e0b8e1323ccb9608cb1726a181e7b04e8a
