apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
- cronjob-backup-db.yaml
sortOptions:
  order: fifo
images:
- name: PROJECT/IMAGE
  newName: cupaxxhd/todo-apps
- name: cupaxxhd/todo-apps
  newName: cupaxxhd/todo-apps
  newTag: e79af4e0b8e1323ccb9608cb1726a181e7b04e8a
