apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
- cronjob-backup-db.yaml
sortOptions:
  order: fifo
images:
- name: PROJECT/IMAGE
  newName: cupaxxhd/todo-apps
- name: cupaxxhd/todo-apps
  newName: cupaxxhd/todo-apps
  newTag: "4.9"
