apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: STAGING_MODE
        value: "true"
  target:
    kind: Deployment
    name: broadcaster
sortOptions:
  order: fifo
images:
- name: PROJECT/IMAGE
  newName: cupaxxhd/broadcaster
  newTag: e527a8a5db1b944377774052b1b7489cf6b6d560
- name: cupaxxhd/broadcaster
  newName: cupaxxhd/broadcaster
  newTag: f2998f459fe89553e3f48b2e343e78568f383957
